/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 07 21:24:02 GMT 2019
 */

package view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.opentest4j.AssertionFailedError;
import view.PersonTableModelTest;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PersonTableModelTest_ESTest extends view.PersonTableModelTest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PersonTableModelTest personTableModelTest0 = new PersonTableModelTest();
      personTableModelTest0.setUp();
      personTableModelTest0.testSeekPersons();
      // Undeclared exception!
      try { 
        personTableModelTest0.testTableModelBasic();
        fail("Expecting exception: AssertionFailedError");
      
      } catch(AssertionFailedError e) {
         //
         // expected: <5> but was: <9>
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PersonTableModelTest personTableModelTest0 = new PersonTableModelTest();
      // Undeclared exception!
      try { 
        personTableModelTest0.testTableModelBasic();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("view.PersonTableModelTest", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      PersonTableModelTest personTableModelTest0 = new PersonTableModelTest();
      personTableModelTest0.setUp();
      personTableModelTest0.testTableModelBasic();
      // Undeclared exception!
      try { 
        personTableModelTest0.testSeekPersons();
        fail("Expecting exception: AssertionFailedError");
      
      } catch(AssertionFailedError e) {
         //
         // expected: <1> but was: <0>
         //
         verifyException("org.junit.jupiter.api.AssertionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[7];
      PersonTableModelTest.main(stringArray0);
      assertEquals(7, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PersonTableModelTest personTableModelTest0 = new PersonTableModelTest();
      // Undeclared exception!
      try { 
        personTableModelTest0.testSeekPersons();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("view.PersonTableModelTest", e);
      }
  }
}
